services:
  app:
    build:
      args:
        user: example
        uid: '1000'
      context: ./
      dockerfile: ./docker-compose/php/Dockerfile
    image: example
    container_name: ${DOCKER_PREFIX}-app
    restart: unless-stopped
    working_dir: /home/www
    volumes:
      - ./:/home/www
      - ./docker-compose/php/conf.d/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
    networks:
      - example
    extra_hosts:
      - ${DOCKER_EXTRA_HOSTS:-host-gateway:host-gateway}
    depends_on:
      - db
      - nginx      


  db:
    image: postgres:13
    container_name: ${DB_HOST}
    restart: unless-stopped
    ports:
      - ${DOCKER_DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - example

  nginx:
    image: nginx:alpine
    container_name: ${DOCKER_PREFIX}-nginx
    restart: unless-stopped
    ports:
      - ${DOCKER_HTTPS_PORT}:443
      - ${DOCKER_HTTP_PORT}:80
    volumes:
      - ./:/home/www
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
      - ./docker-compose/nginx/ssl:/etc/nginx/ssl
    networks:
      - example

networks:
  example:
    driver: bridge

volumes:
  pgdata:
    driver: local
